# Generated by Django 3.2.5 on 2021-07-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210409_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=120)),
                ('make', models.CharField(max_length=120)),
                ('Variant', models.CharField(max_length=120)),
                ('price', models.FloatField(max_length=120)),
                ('fuel_type', models.CharField(max_length=120)),
                ('Link', models.CharField(max_length=2000)),
                ('image_link', models.CharField(max_length=2000)),
            ],
        ),
    ]
